[build]
  publish = "."

[[headers]]
  for = "/menus.json"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
